forever(function () {
    music.play(music.createSong(assets.song`Action1`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action2`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action3`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action4`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action5`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action6`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action7`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action8`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action9`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action10`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action11`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action12`), music.PlaybackMode.UntilDone)
    music.play(music.createSong(assets.song`Action13`), music.PlaybackMode.UntilDone)
})
